import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// Marketing pages live under src/pages (index, playground).
// Docs content lives under src/content/docs/docs/ so Starlight serves it at /docs
// rather than claiming / from the landing page. Same build.
// Deploy target: Cloudflare Pages (static output).
//
// `site` and Starlight's social links are intentionally unset until the domain
// is registered and the GitHub repo exists — no placeholder URLs. The sidebar is
// autogenerated until docs sections have real content.
export default defineConfig({
  integrations: [
    starlight({
      title: "Jotstak Docs",
    }),
  ],
});
