import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import remarkJotDemo from "./plugins/remark-jot-demo.mjs";

const DEV = process.argv.includes("dev");
const CONTENT = new URL("./src/content/docs/", import.meta.url);

/**
 * A sidebar group, or nothing if every page in it is still a draft.
 *
 * The docs are being written section by section, and a shell page carries
 * `draft: true` so it stays out of the built site. Starlight drops the pages
 * but keeps the group, which left the public sidebar advertising five empty
 * sections. So a group whose pages are all drafts is dropped here too — while
 * `astro dev` shows every one of them, which is the whole point of writing the
 * shell first.
 */
function group(label, directory, extra = {}) {
  const dir = new URL(`./${directory}/`, CONTENT);
  const pages = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".md") || f.endsWith(".mdx")) : [];
  const published = pages.some((f) => !/^draft:\s*true\s*$/m.test(readFileSync(new URL(f, dir), "utf8")));
  if (!DEV && !published) return null;
  return { label, ...extra, items: [{ autogenerate: { directory } }] };
}

// Marketing pages live under src/pages (index, playground).
// Docs content lives under src/content/docs/docs/ so Starlight serves it at /docs
// rather than claiming / from the landing page. Same build.
// Deploy target: Cloudflare Pages (static output).
//
export default defineConfig({
  // Demos are rendered in the Markdown pipeline, not as components: Astro's
  // per-instance compilation cost made ~38 component demos exhaust the heap.
  markdown: { remarkPlugins: [remarkJotDemo] },
  site: "https://jotstak.pages.dev",
  integrations: [
    starlight({
      title: "Jotstak Docs",
      // The wordmark is near-black ink; on Starlight's dark theme it vanishes.
      // A cream-ink variant is swapped in for dark mode.
      logo: {
        light: "./src/assets/lockup.svg",
        dark: "./src/assets/lockup-dark.svg",
        alt: "Jotstak",
        replacesTitle: true,
      },
      favicon: "/favicon.svg",
      head: [
        { tag: "link", attrs: { rel: "icon", href: "/favicon-32.png", sizes: "32x32", type: "image/png" } },
        { tag: "link", attrs: { rel: "apple-touch-icon", href: "/apple-touch-icon.png" } },
        { tag: "meta", attrs: { name: "theme-color", content: "#c67139" } },
        { tag: "link", attrs: { rel: "stylesheet", href: "/jotstak-demo.css" } },
        { tag: "meta", attrs: { property: "og:image", content: "https://jotstak.pages.dev/og.png" } },
        { tag: "meta", attrs: { name: "twitter:card", content: "summary_large_image" } },
      ],
      // Grouped by what the reader is trying to do, not by what the tool is
      // made of. "Functions" is a reference you arrive at knowing the name of
      // the thing; every group above it is for readers who do not yet.
      //
      // Most pages under guide/ and cookbook/ are still shells (draft: true)
      // and so are absent from a production build — which is also why those
      // groups are autogenerated rather than listed by hand: a group empties
      // itself as the drafts drop out.
      sidebar: [
        {
          label: "Get started",
          items: [
            { label: "Overview", link: "/docs/" },
            { label: "Quick start", link: "/docs/start/" },
          ],
        },
        group("Writing documents", "docs/guide"),
        group("Cookbook", "docs/cookbook"),
        {
          label: "Reference",
          items: [
            { autogenerate: { directory: "docs/reference" } },
            // One page per rendering function, ordered by the generator.
            // Starlight gives prev/next across a group for free.
            { label: "Functions", collapsed: true, items: [{ autogenerate: { directory: "docs/functions" } }] },
          ],
        },
        {
          label: "Resources",
          items: [
            { label: "Patterns", link: "/docs/recipes/" },
            { autogenerate: { directory: "docs/resources" } },
          ],
        },
      ].filter(Boolean),
      social: [
        { icon: "github", label: "GitHub", href: "https://github.com/Semilore-James/jotstak" },
      ],
    }),
  ],
});
