// GENERATED by scripts/extract-font-metrics.mjs — do not edit by hand.
// Run `npm run metrics -w @jotstak/renderer` to regenerate after a font bump.
//
// Measured from the woff2 files actually shipped, because the baseline offset
// that puts text ON the ruled line is computed from these numbers (ADR-002).

export interface FontMetrics {
  family: string;
  unitsPerEm: number;
  /** Ascent above the baseline, in em. */
  ascent: number;
  /** Descent below the baseline, in em (positive). */
  descent: number;
  lineGap: number;
  /** Mean advance width of a–z, in em. Used to size metric-matched fallbacks. */
  meanLowercaseAdvance: number;
}

export const FONT_METRICS = {
  "lora": {
    "family": "Lora",
    "unitsPerEm": 1000,
    "ascent": 1.006,
    "descent": 0.274,
    "lineGap": 0,
    "meanLowercaseAdvance": 0.524
  },
  "caveat": {
    "family": "Caveat",
    "unitsPerEm": 1000,
    "ascent": 0.96,
    "descent": 0.3,
    "lineGap": 0,
    "meanLowercaseAdvance": 0.3632
  }
} as const satisfies Record<string, FontMetrics>;
